// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StellarisCharts.Api.Data;

#nullable disable

namespace StellarisCharts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128094500_AddSpeciesPopulations")]
    partial class AddSpeciesPopulations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StellarisCharts.Api.Models.BudgetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("SnapshotId", "CountryId", "Section");

                    b.ToTable("BudgetLineItems");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capital")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EconomyPower")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpireSize")
                        .HasColumnType("integer");

                    b.Property<int>("FleetSize")
                        .HasColumnType("integer");

                    b.Property<string>("GovernmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraphicalCulture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MilitaryPower")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NumSapientPops")
                        .HasColumnType("bigint");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TechPower")
                        .HasColumnType("numeric");

                    b.Property<int>("VictoryRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("VictoryScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EconomyPower")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpireSize")
                        .HasColumnType("integer");

                    b.Property<int>("FleetSize")
                        .HasColumnType("integer");

                    b.Property<string>("GameDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MilitaryPower")
                        .HasColumnType("numeric");

                    b.Property<long>("NumSapientPops")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TechPower")
                        .HasColumnType("numeric");

                    b.Property<int>("Tick")
                        .HasColumnType("integer");

                    b.Property<int>("VictoryRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("VictoryScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.SpeciesPopulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("SnapshotId", "CountryId", "SpeciesId");

                    b.ToTable("SpeciesPopulations");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.BudgetLineItem", b =>
                {
                    b.HasOne("StellarisCharts.Api.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasPrincipalKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StellarisCharts.Api.Models.Snapshot", "Snapshot")
                        .WithMany("BudgetLineItems")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.Snapshot", b =>
                {
                    b.HasOne("StellarisCharts.Api.Models.Country", "Country")
                        .WithMany("Snapshots")
                        .HasForeignKey("CountryId")
                        .HasPrincipalKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.SpeciesPopulation", b =>
                {
                    b.HasOne("StellarisCharts.Api.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasPrincipalKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StellarisCharts.Api.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.Country", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("StellarisCharts.Api.Models.Snapshot", b =>
                {
                    b.Navigation("BudgetLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
